server:
  port: 8082

spring:
  application:
    name: apex-crud
  datasource:
    url: jdbc:mariadb://localhost:3306/apex_crud
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG
