server:
  port: 9090

#springdoc:
#  paths-to-match: "/api/v1/**", "/auth/**"
#  packages-to-scan: com.bjit.demo_blog.controllers

spring:
  application:
    name: apex-crud
  datasource:
    url: jdbc:mariadb://localhost:3306/apex_crud
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB

  security:
    user:
      name: shariar
      password: shariar
      roles: ADMIN

#project:
#  image: images/

logging:
  level:
    org.springframework.security: DEBUG

#server:
#  servlet:
#    context-path: "/api/**"

# Gmail configuration
#mail:
#  host: smtp.gmail.com
#  port: 587
#  username: itmasjoy@gmail.com
#  password: ezifuujyayteujxr
#  properties:
#    mail:
#      smtp:
#        auth: true
#        starttls:
#          enable: true
